INSERT INTO PUBLIC.INBOUND (INBD_ID, INBD_CHANNEL_ID, INBD_TIME, INBD_STATUS) VALUES ('1', 777, '2018-09-05 17:36:26.649000000', 11);
INSERT INTO PUBLIC.INBOUND (INBD_ID, INBD_CHANNEL_ID, INBD_TIME, INBD_STATUS) VALUES ('QQQ', 666, '2018-09-05 17:36:26.649000000', 22);

INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('2', 'TXT_FILE', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('21', 'TXT_FILE1', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('22', 'TXT_FILE2', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('23', 'TXT_FILE3', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('24', 'TXT_FILE4', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('25', 'TXT_FILE5', '1 MB', 'QQQ');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('222', 'TXT_FILE', '1 MB', '1');
INSERT INTO PUBLIC.PREPROCESSING (PREPROC_ID, PREPROC_FILE_TYPE, PREPROC_FILE_SZE, PREPROC_INBD_ID) VALUES ('223', 'TXT_FILE', '1 MB', '1');

INSERT INTO PUBLIC.PROCESSING (PROC_ID, PROC_CUSTOMER_ID, PROC_COUNTERPARTY_ID, PROC_TYPE, PROC_BUSINESS_TYPE, PROC_STATUS, PROC_PREPROC_ID) VALUES ('3', 'CUST_ID', 'CTRPARTY_ID', 234, 'BIG_DEAL', 333, '2');

INSERT INTO PUBLIC.POSTPROCESSING (POSTPROC_ID, POSTPROC_TYPE, POSTPROC_FORMAT, POSTPROC_PROC_ID) VALUES ('4', 'post processing', 'XML', '3');

INSERT INTO PUBLIC.OUTBOUND (OUTBOUND_ID, OUTBOUND_CHANNEL_ID, OUTBOUND_STATUS, OUTBOUND_POSTPROC_ID) VALUES ('5', 'OUT_CHANNEL_ID_ROW', 5, '4');